version: '3.7'

services:

  db:

    image: postgres:13-alpine
    container_name: forecast_db

    ports:
      - "5432:5432"
    
    environment:
      - POSTGRES_USER=forecast_user
      - POSTGRES_PASSWORD=forecast_pass
      - POSTGRES_DB=forecast_db

    volumes:
      - ./postgres-data:/var/lib/postgresql/data